export enum UserFieldName {
    ID = '_id',
    EMAIL = 'email',
    PASSWORD = 'password',
    USER_NAME = 'user_name',
    PHONE = 'phone',
    FULL_NAME = 'full_name',
    AVATAR_URL = 'avatar_url',
    ROLE_CODE = 'role_code',
    IS_VERIFIED = 'is_verified',
    VERIFICATION_TOKEN = 'verification_token',
    VERIFICATION_TOKEN_EXPIRES = 'verification_token_expires',
    TOKEN_VERSION = 'token_version',
    IS_BLOCKED = 'is_blocked',
}